services:
  - type: web
    name: zvertex3d-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
<<<<<<< HEAD
      - key: SUPABASE_SECRET_KEY
        sync: false
=======
>>>>>>> 198dc3267cce374489a058aa74e737c1402dcabb
>>>>>>> 4ff7eff4da625b0aa81943bb92486aeaeca350f5
>>>>>>> bfa6eea49934b7beb4ebc42a1ae246db25ad53c1
>>>>>>> a6a3db8e95390c1e7f8a89f32fc719b550f6b66b
>>>>>>> 6749823fb1f85adf6e3b7e3523847c8ec5eea842
>>>>>>> 5fe4c532631c49952bf7e16bbac69a863f154676
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
<<<<<<< HEAD
        value: https://zvertex3d.com,https://www.zvertex3d.com
=======
        sync: false
>>>>>>> 198dc3267cce374489a058aa74e737c1402dcabb
>>>>>>> 4ff7eff4da625b0aa81943bb92486aeaeca350f5
>>>>>>> bfa6eea49934b7beb4ebc42a1ae246db25ad53c1
>>>>>>> a6a3db8e95390c1e7f8a89f32fc719b550f6b66b
>>>>>>> 6749823fb1f85adf6e3b7e3523847c8ec5eea842
>>>>>>> 5fe4c532631c49952bf7e16bbac69a863f154676
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
