import { useState } from "react";
import { ArrowRight, Check, Store } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { registerVendor } from "../services/api";

export default function VendorRegister() {
  const [form,setForm]=useState({name:"",email:"",password:"",storeName:"",phone:"",city:"",tagline:"",description:""});
  const [done,setDone]=useState(false); const navigate=useNavigate();
  const submit=async e=>{e.preventDefault();try{await registerVendor(form);setDone(true)}catch(err){alert(err.response?.data?.message||"Registration failed.")}};
  if(done) return <section className="center-page"><div className="success-card"><div className="success-icon">✓</div><div className="eyebrow">APPLICATION RECEIVED</div><h1>Your store is in review.</h1><p className="muted">Zvertex3D will review your business details before publishing your storefront.</p><Link className="button primary" to="/login">Go to sign in</Link></div></section>;
  return <section className="auth-page"><div className="auth-card wide"><div className="auth-intro"><div className="brand-mark"><Store size={20}/></div><div className="eyebrow">VENDOR NETWORK</div><h1>Open your Zvertex3D store.</h1><p className="muted">Get a branded storefront, access manufacturing orders and let Zvertex3D handle marketplace discovery.</p><div className="check-list compact"><span><Check/> Store page on your own Zvertex3D URL</span><span><Check/> Manage products and orders</span><span><Check/> Admin-controlled approval</span></div></div>
    <form onSubmit={submit} className="form-stack"><div className="field-grid two"><label>Owner name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Business/store name<input required value={form.storeName} onChange={e=>setForm({...form,storeName:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label>Store tagline<input placeholder="e.g. Precision printing for product teams" value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><label>About your business<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="button primary full">Submit vendor application <ArrowRight size={17}/></button><small className="muted">Already approved? <Link to="/login">Sign in here.</Link></small></form>
  </div></section>;
}