const router=require('express').Router(); const multer=require('multer'); const sharp=require('sharp'); const {supabase}=require('../config/db'); const {rowToAsset}=require('../lib/data'); const {heightmapToStl}=require('../utils/stl');
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
<<<<<<< HEAD
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(file.mimetype))});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=Buffer.from(result.stl,'utf8').toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed.',error:e.message});}});
=======
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>{if(/^image\/(png|jpeg|webp)$/.test(file.mimetype)) return cb(null,true); cb(new Error('Only PNG, JPEG or WebP images are supported.'));}});
router.post('/heightmap',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Image is required.'});const widthMm=Math.min(300,Math.max(20,Number(req.body.width)||100));const depthMm=Math.min(300,Math.max(20,Number(req.body.depth)||100));const heightMm=Math.min(30,Math.max(1,Number(req.body.height)||8));const raw=await sharp(req.file.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});const {data,info}=raw;const result=heightmapToStl(data,info.width,info.height,widthMm,depthMm,heightMm);const stlBase64=result.stl.toString('base64');const r=await supabase.from('model_assets').insert({original_name:req.file.originalname,mime_type:'model/stl',stl_base64:stlBase64,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices,source_width:info.width,source_height:info.height}).select('*').single();if(r.error)throw r.error;const asset=rowToAsset(r.data);res.status(201).json({id:asset.id,stlUrl:`${req.protocol}://${req.get('host')}/api/models/${asset.id}/stl`,width:widthMm,depth:depthMm,height:heightMm,vertices:result.vertices});}catch(e){console.error(e);res.status(500).json({message:'STL generation failed. Please try a PNG, JPEG or WebP image under 10 MB.',error:e.message});}});
>>>>>>> 198dc3267cce374489a058aa74e737c1402dcabb
>>>>>>> 4ff7eff4da625b0aa81943bb92486aeaeca350f5
>>>>>>> bfa6eea49934b7beb4ebc42a1ae246db25ad53c1
>>>>>>> a6a3db8e95390c1e7f8a89f32fc719b550f6b66b
>>>>>>> 6749823fb1f85adf6e3b7e3523847c8ec5eea842
>>>>>>> 5fe4c532631c49952bf7e16bbac69a863f154676
>>>>>>> f5f7d408740acf640b490ad955179b89f222a19c
>>>>>>> 0e9e6f07bd68a8be2c5da3b5054c33dec9b12c54
>>>>>>> 9b96cf9f299962791c8d548b0cb442523367cf3e
router.get('/:id',async(req,res)=>{const r=await supabase.from('model_assets').select('id,original_name,mime_type,width,depth,height,vertices,source_width,source_height,created_at,updated_at').eq('id',req.params.id).maybeSingle();if(r.error)return res.status(500).json({message:r.error.message});if(!r.data)return res.status(404).json({message:'Model not found.'});res.json(rowToAsset(r.data));});
router.get('/:id/stl',async(req,res)=>{const r=await supabase.from('model_assets').select('original_name,stl_base64').eq('id',req.params.id).maybeSingle();if(r.error)return res.status(500).json({message:r.error.message});if(!r.data)return res.status(404).end();const safe=(r.data.original_name||'model').replace(/[^a-zA-Z0-9._-]/g,'_').replace(/\.[^.]+$/,'');res.set({'Content-Type':'model/stl','Content-Disposition':`inline; filename="${safe}.stl"`,'Cache-Control':'public, max-age=86400'});res.send(Buffer.from(r.data.stl_base64,'base64'));});
module.exports=router;
