require('dotenv').config({path:require('path').join(__dirname,'.env')});
const express=require('express'); const cors=require('cors'); const helmet=require('helmet'); const rateLimit=require('express-rate-limit');
const {connectDB,closeDB}=require('./config/db');
const authRoutes=require('./routes/auth'); const vendorRoutes=require('./routes/vendors'); const modelRoutes=require('./routes/models'); const orderRoutes=require('./routes/orders'); const adminRoutes=require('./routes/admin');
const app=express(); app.set('trust proxy',1); app.use(helmet());
app.use(cors({origin:(origin,cb)=>{const allowed=(process.env.CLIENT_URL||'').split(',').map(x=>x.trim()).filter(Boolean);if(!origin||allowed.length===0||allowed.includes(origin))return cb(null,true);cb(new Error('CORS blocked'));}}));
app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
let dbReady=false;
app.get('/health',(req,res)=>res.status(dbReady?200:503).json({ok:dbReady,service:'zvertex3d-api',database:dbReady?'supabase-postgresql':'disconnected',time:new Date().toISOString()}));
app.use('/api/auth',authRoutes); app.use('/api/vendors',vendorRoutes); app.use('/api/models',modelRoutes); app.use('/api/orders',orderRoutes); app.use('/api/admin',adminRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({message:err.message||'Server error.'});});
const port=process.env.PORT||5000;
connectDB().then(()=>{dbReady=true;const server=app.listen(port,'0.0.0.0',()=>console.log(`API listening on ${port}`));const shutdown=async()=>{server.close(async()=>{await closeDB();process.exit(0);});};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);}).catch(err=>{console.error(err);process.exit(1);});
