const nodemailer=require("nodemailer");
const COMMUNICATION_EMAIL=process.env.MAIL_FROM||"zvertex3d@gmail.com";
let transporter=null;
function getTransporter(){if(transporter)return transporter;if(!process.env.SMTP_HOST)return null;transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==="true",auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined});return transporter;}
async function sendMail({to,subject,html,text}){const tx=getTransporter();if(!tx){console.warn(`[Zvertex3D mail] SMTP not configured. To: ${to} | Subject: ${subject}`);return {sent:false,reason:"smtp_not_configured"};}await tx.sendMail({from:COMMUNICATION_EMAIL,to,subject,html,text,replyTo:COMMUNICATION_EMAIL});return {sent:true};}
async function sendSignupConfirmation(user){return sendMail({to:user.email,subject:"Welcome to Zvertex3D",text:`Hi ${user.name||'there'}, your Zvertex3D account has been created successfully. You can sign in now.`,html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h2>Zvertex3D</h2><p>Hi ${user.name||'there'},</p><p>Your Zvertex3D account has been created successfully.</p><p>No email verification is required. You can sign in immediately.</p><p>Thank you,<br>Zvertex3D Team</p></div>`});}
async function sendVendorApplicationConfirmation(vendor){return sendMail({to:vendor.email,subject:"Zvertex3D vendor application received",text:`Hi ${vendor.name||'there'}, your vendor application for ${vendor.storeName} was received and is pending admin approval.`,html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h2>Zvertex3D Vendor Network</h2><p>Hi ${vendor.name||'there'},</p><p>We received your vendor application for <strong>${vendor.storeName}</strong>.</p><p>Your application is now <strong>pending admin approval</strong>. Once approved, your store will automatically appear in the Zvertex3D Marketplace.</p><p>No email verification is required.</p><p>Regards,<br>Zvertex3D Team<br>${COMMUNICATION_EMAIL}</p></div>`});}
async function sendAdminNotification(subject,html,text){const to=process.env.ADMIN_EMAIL||COMMUNICATION_EMAIL;return sendMail({to,subject,html,text});}
async function sendVendorStatusEmail(vendor,status){const subject=`Zvertex3D vendor application: ${status}`;return sendMail({to:vendor.email,subject,text:`Your Zvertex3D vendor application is now ${status}.`,html:`<div style="font-family:Arial,sans-serif"><h2>Zvertex3D Vendor Network</h2><p>Hello ${vendor.name},</p><p>Your vendor application for <strong>${vendor.storeName}</strong> is now <strong>${status}</strong>.</p>${status==='approved'?'<p>Your store is now live in the Zvertex3D Marketplace.</p>':''}<p>Thank you,<br/>Zvertex3D Team<br/>${COMMUNICATION_EMAIL}</p></div>`});}
async function sendOrderEmails(order,vendor){const subject=`Zvertex3D order ${order.orderNumber} received`;const customerHtml=`<div style="font-family:Arial,sans-serif"><h2>Zvertex3D</h2><p>Hi ${order.customer.name},</p><p>Your manufacturing request <strong>${order.orderNumber}</strong> has been sent to <strong>${vendor.storeName}</strong>.</p><p>Estimated value: ₹${Number(order.estimatedPrice||0).toLocaleString("en-IN")}</p><p>Zvertex3D will keep you updated.</p><p>${COMMUNICATION_EMAIL}</p></div>`;const vendorHtml=`<div style="font-family:Arial,sans-serif"><h2>Zvertex3D Manufacturing Network</h2><p>New order <strong>${order.orderNumber}</strong> has been assigned to your approved store <strong>${vendor.storeName}</strong>.</p><p>Customer: ${order.customer.name} · ${order.customer.email} · ${order.customer.phone}</p></div>`;await Promise.all([sendMail({to:order.customer.email,subject,text:`Order ${order.orderNumber} received by Zvertex3D.`,html:customerHtml}),sendMail({to:vendor.email,subject,text:`New Zvertex3D order ${order.orderNumber}.`,html:vendorHtml}),sendAdminNotification(subject,vendorHtml,`New order ${order.orderNumber} for ${vendor.storeName}.`)]);}
module.exports={sendMail,sendSignupConfirmation,sendVendorApplicationConfirmation,sendAdminNotification,sendVendorStatusEmail,sendOrderEmails};
